### ISSUE TITLE
Type or Namespace QRCode could not be found error

### ISSUE THREAD

**Issue by vrsolankiGH** [YogeshHadiya33/QRCodeInASPNetCore#1]
![image](https://user-images.githubusercontent.com/79351460/217479662-66eaa3f8-8d6d-4d5b-a187-cb191edcc9bb.png)

**Comment by YogeshHadiya33** [comment]
Hello,

You'll need to install QRCoder NuGet package. If you already installed it, it may conflict with your class or controller name. Please verify that your user-define class does not have a similar name to these classes.
